name: flutter_app_responsive_auction_mockup
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  auto_route: ^0.6.9
  sized_context: ^0.2.1+1
  flutter_bloc: ^6.0.1
  equatable: ^1.2.5
  dartz: ^0.9.2
  get_it: ^5.0.6
  freezed_annotation: ^0.12.0
  data_connection_checker: ^0.3.4
  flutter_svg: ^0.18.0
  change_app_package_name: ^0.1.2
  keyboard_visibility: ^0.5.6
  sms_autofill: ^1.2.3
  fluttertoast: ^6.0.1
  smooth_page_indicator: ^0.2.0
  injectable: ^1.0.4
  masked_text_input_formatter: ^0.0.1
  page_turn: ^1.0.1
  dots_indicator: ^1.2.0
dependency_overrides:


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  freezed: ^0.12.7
  injectable_generator: ^1.0.4
#  json_serializable: ^3.4.0
  lint: ^1.0.0
  build_runner: ^1.10.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/svg/
#      - assets/images/bluebg/
#      - assets/images/logo/
      - assets/static/
      - assets/images/aras/
      - assets/images/creditlogo/
#      - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: opensans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf


    - family: libre
      fonts:

            - asset: assets/fonts/LibreBaskerville-Regular.ttf

  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
